title: Sai Kumar # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Pursuing MBA in Big Data Analytics(BDA) from Goa Institute of Management with a keen interest in Data Science, Machine Learning, and NLP. Demonstrated expertise through internships at Tiger Analytics and Merck & Co.
  <br> 
  Ranked in top 10% of the batch.<br> 
  MBA  - 6.52/8 <br> 
  Engg - 9.00/10
  <br>
  <a href="https://www.linkedin.com/in/sai-kumar-99ba9b88/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
